### PR TITLE
fix(main): wrong commands were triggering envFile search

### LINKED ISSUE #28: infra:new is falling because of var file check
The command infra:new is triggering the `pulumi stack ls` which fails because no Pulumi.yaml exists. We need to remove the environment variable file check for this command.

### PR DESCRIPTION
**Pull request by kaiquelupo**
Commands such as infra:new are triggering the env file search which in turn executes pulumi stack ls. As in this moment there is no Pulumi.yaml file yet, the command fails.

fix #28

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -57,27 +57,25 @@ function getEnvironmentVariables(twilioClient, shouldGetEnvFromFile) {
...
  * @param {Array} args Arguments to Pulumi CLI command
- * @param {boolean=true} interactive Whether to run the command in interactive mode (i.e. gathering input from user)
+ * @param {boolean} checkEnvFile Whether to search and load env file for the current stack 
+ * @param {boolean=true} interactive Whether to run the command in interactive mode (i.e. gathering input from user) 
  * @param {{}} twilioClient Initialized Twilio client
  * @return {null | string} Pulumi command output if executed non interactively. Void if execute interactively
  */
 
-function runPulumiCommand(args, interactive = true, twilioClient) {
+function runPulumiCommand(args, checkEnvFile, interactive = true, twilioClient) {
```
Comment (vernig) [inline src/utils.js]: @kaiquelupo is there a better way to implement this without adding an argument to the `runPulumiCommand()`? I'd rather handle all the _internals_ of Pulumi CLI commands within the  `runPulumiCommand()`. We should see this function as adaption layer that abstract third party tool, so in the future we can add / replace pulumi with other provider as well.

**Review by vernig — CHANGES_REQUESTED** [review]

File: src/utils.js (hunk 1 above)
Comment (kaiquelupo) [reply src/utils.js]: Got it, makes sense. The other way would be adding 

`    const shouldGetEnvFromFile = 
      (args[0] !== "stack" && args[1] !== "ls") && 
      (args[0] !== "new");`

to the runPulumiCommand and return everything else to how they were.

My only concern is that we are listing the commands we don't want to seach for the env file  and I am not sure if this approach is better then the one on this PR right now. What do you think @vernig ?

Comment (vernig) [reply src/utils.js]: Yes, I think this is a more straightforward implementation because it requires changes in one single place. So if in the future we want to change this implementation, we don't have to change all the places where we call the `runPulumiCommand()`.

Comment (kaiquelupo) [reply src/utils.js]: Right! I will make the change now
